### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by 8auer** [cubernetes/TikTokCommentScraper#6]
stopped working with following error in console :  

init.js?cache:1          POST https://mon-va.byteoversea.com/monitor_browser/collect/batch/ net::ERR_BLOCKED_BY_CLIENT

**Comment by Belissimo-T** [comment]
This error is not the cause of the problem. Look at the fixed file of PR #7 to see the fixed js code that sadly has also stopped working. I suspect your error is caused by your AdBlocker.
