### ISSUE TITLE
Issue with Java Script

### ISSUE THREAD

**Issue by Donovan-Adams** [cubernetes/TikTokCommentScraper#8]
When I try to run the Java Script in the Console in Developer Tools, this error pops up and won't extract comments. Could you explain why and how to fix this? Thank you!

VM2732:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at getAllComments (<anonymous>:28:55)
    at <anonymous>:64:37
    at <anonymous>:156:3

**Comment by HenryBlackie** [comment]
I've been getting the exact same issue. I've tried using Brave, Chrome, and Firefox with adblockers enabled and disabled and it has not resolved the problem.

**Comment by katstasaph** [comment]
Basically, TikTok changed its layout, and the paths from that version are no longer accurate to what's on the site. The JavaScript code from the pull request I have up works on the most recent version.
