### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ')'

### ISSUE THREAD

**Issue by HenryBlackie** [cubernetes/TikTokCommentScraper#9]
When I attempt to run the latest script I get an error saying there's an unexpected token in line 197 (screenshot 1).

When I opened src/ScrapeTikTokComments.js in Sublime it also highlights the same character (screenshot 2). Removing this character does not appear to fix the issue as I get the same error message (screenshot 3). When I remove the last 3 characters `)()` then the script appears to work correctly (screenshot 4).

I've never coded in JS, so I'm not sure if these changes break something. But if other people are having the same issue then this change may be needed.

Screenshot 1
![image](https://user-images.githubusercontent.com/5684989/200185919-c7601807-6b0d-44e1-a8ff-4b42ecbd53ab.png)
Screenshot 2
![image](https://user-images.githubusercontent.com/5684989/200186096-844d26b0-7f95-4478-a486-44a3ef1b7c0f.png)
Screenshot 3
![image](https://user-images.githubusercontent.com/5684989/200186358-5bbbf803-3ff3-4d10-b93a-208a3bd4dfb5.png)
Screenshot 4
![image](https://user-images.githubusercontent.com/5684989/200186433-68ed483e-30f4-4184-993d-19d39e86a298.png)

**Comment by jacoblhughes** [comment]
Thank you!

**Comment by jeffreyxparker** [comment]
Also encountered this

**Comment by welovejeff** [comment]
This also fixed it for me, going to try and submit a change to the project.
